README.md
=> notify to phabricator on PR

.github/workflows/notification.yaml
=> Workflow headings

.github/workflows/notification.yaml
=> Update PR on close

.github/workflows/notification.yaml
=> Comment to phabricator on PR close

quarry/web/static/js/query/view.js
Mostly re-hashing https://github.com/toolforge/quarry/pull/4
Bug: T126540
=> T126540: More dropdown options for page length

quarry/web/results.py, tests/test_results.py
Bug: T170464
Change-Id: I12d3f10447b67ca310160092e75708d3f8649ad5
=> results: Don't crash if multiple columns share a name

quarry/default_config.yaml, quarry/web/app.py, quarry/web/templates/landing.html, requirements.txt, tests/conftest.py, tests/test_app.py
cache this part of the homepage for 30s using caching lib. Be careful to not cache full page, otherwise username will not be updated when login
Bug: T204157
=> Add statistics on the homepage

Dockerfile, docker-replica/replica.sql, quarry/web/app.py, quarry/web/static/templates/compiled.js, quarry/web/static/templates/query-status.html, quarry/web/templates/landing.html, quarry/web/webhelpers.py, quarry/web/worker.py, tests/test_worker.py
Add a warning while there is replication lag on dbs
Bug: T60841
=> Advertise on replag

.github/workflows/update-container-tags.yaml, helm-quarry/values.yaml
=> Update helm on pr

helm-quarry/values.yaml, quarry/web/static/js/query/view.js
=> Do not offer stop button on queued

.github/workflows/linter.yaml, helm-quarry/values.yaml, tests/tox/Dockerfile, tox.ini
=> Tox separate from blubber

helm-quarry/values.yaml, quarry/web/static/templates/compiled.js, quarry/web/static/templates/query-status.html
=> Show Explain button only if query is running

.github/workflows/build-and-push.yaml, helm-quarry/values.yaml
=> Build branch, not main

helm-quarry/values.yaml, tofu/124.tf, tofu/vars.tf
This also rotates the app cred because it's due.
=> Move quarry deployment to ovs (via g4 flavors)

deploy.sh, helm-quarry/values.yaml
=> Upgrade ansible

helm-quarry/templates/redis_statefulset.yaml, helm-quarry/values.yaml
- **helm: Convert Redis to a StatefulSet**
- **helm: Use a volume for Redis data**
Bug: T392141
=> helm: Improve Redis handling

helm-quarry/prod-env.yaml, helm-quarry/values.yaml
I can't think of why we would need that many replicas here - let's try
reducing that and see what happens.
Bug: T392143
Change-Id: I56958f28d0768cb47b2de97c5fc514371f9729d8
=> helm: Reduce number of web replicas

README.md, helm-quarry/values.yaml, tofu/127b.tf
- Remove definition for old 127a deploy
- Add definition for new 127b deploy (which is already running)
- Add docs about blue/green deployment
- Update network name to catch up with eqiad1 network refactors
=> New deploy w/new network name

helm-quarry/dev-env.yaml, helm-quarry/prod-env.yaml, helm-quarry/templates/redis_statefulset.yaml, helm-quarry/templates/web_deployment.yaml, helm-quarry/templates/worker_deployment.yaml, helm-quarry/values.yaml
- **helm: Make resources more easily configurable**
- **helm: Set limits for Quarry pods as well**
- **helm: Set resources for Redis**
=> Set some resource limits

.github/workflows/update-container-tags.yaml
Change-Id: I52a036a19acd860297f2c294551768b7c7d71a15
=> build: Update add-and-commit action
